const CONFIG = {
  days: {
    A: [
      { name: 'Desenv no Smith 3x15', sets: 3, reps: 15 },
      { name: 'Desenv no Smith 3x10', sets: 3, reps: 10 },
      { name: 'Desenv no Smith 2x6', sets: 2, reps: 6 },
      { name: 'Desenv Halteres', sets: 3, reps: 8 },
      { name: 'Elev Lateral Cabo', sets: 4, reps: 10 },
      { name: 'Elev Frontal Barra W', sets: 3, reps: 10 },
      { name: 'Posterior Ombro Voador', sets: 5, reps: 10 },
    ],
    B: [
      { name: 'Remada Curvada 3x15', sets: 3, reps: 15 },
      { name: 'Remada Curvada 3x10', sets: 3, reps: 10 },
      { name: 'Remada Curvada 2x6', sets: 2, reps: 6 },
      { name: 'Serrote 3x15', sets: 3, reps: 15 },
      { name: 'Serrote 3x10', sets: 3, reps: 10 },
      { name: 'Serrote 2x6', sets: 2, reps: 6 },
      { name: 'Puxada Triângulo', sets: 3, reps: 8 },
      { name: 'Pullover Cross Barra', sets: 3, reps: 8 },
      { name: 'Costas Voador Dorsal', sets: 5, reps: 10 },
      { name: 'Rosca Barra Reta Livre 2x15', sets: 2, reps: 15 },
      { name: 'Rosca Barra Reta Livre 2x10', sets: 2, reps: 10 },
      { name: 'Rosca Barra Reta Livre 2x6', sets: 2, reps: 6 },
      { name: 'Rosca Barra Reta Cross 2x15', sets: 2, reps: 15 },
      { name: 'Rosca Barra Reta Cross 2x10', sets: 2, reps: 10 },
      { name: 'Rosca Barra Reta Cross 2x6', sets: 2, reps: 6 },
      { name: 'Rosca Barra W 2x15', sets: 2, reps: 15 },
      { name: 'Rosca Barra W 2x10', sets: 2, reps: 10 },
      { name: 'Rosca Barra W 2x6', sets: 2, reps: 6 },
    ],
    C: [
      { name: 'Agachamento Smith 2x15 (mod)', sets: 2, reps: 15 },
      { name: 'Agachamento Smith 2x8 (pes)', sets: 2, reps: 8 },
      { name: 'Agachamento Smith 3x6 (mt pes)', sets: 3, reps: 6 },
      { name: 'Leg Press 2x15 (mod)', sets: 2, reps: 15 },
      { name: 'Leg Press 2x8 (pes)', sets: 2, reps: 8 },
      { name: 'Leg Press 3x6 (mt pes)', sets: 3, reps: 6 },
      { name: 'Stiff Joelhos SemiFlex 3x15 (mod)', sets: 3, reps: 15 },
      { name: 'Stiff Joelhos SemiFlex 3x8 (pes)', sets: 3, reps: 8 },
      { name: 'Stiff Joelhos Reto 3x15 (mod)', sets: 3, reps: 15 },
      { name: 'Extensora 3x10/15 -30%', sets: 3, reps: 15 },
      { name: 'Flexora 3x10/15 -30%', sets: 3, reps: 15 },
      { name: 'Panturrilha em pé 2x12', sets: 2, reps: 12 },
      { name: 'Panturrilha em pé 2x15', sets: 2, reps: 15 },
      { name: 'Panturrilha em pé 2x20', sets: 2, reps: 20 },
      { name: 'Panturrilha Sentado 2x12', sets: 2, reps: 12 },
      { name: 'Panturrilha Sentado 2x15', sets: 2, reps: 15 },
    ],
    D: [
      { name: 'Supino Reto com Barra 10/15 -30%', sets: 3, reps: 10 },
      { name: 'Peitoral Cross Palma Frente 10/15 -30%', sets: 3, reps: 10 },
      { name: 'Peitoral Cross Soco Baixo 2x15 (mod)', sets: 2, reps: 15 },
      { name: 'Peitoral Cross Soco Baixo 2x8 (pes)', sets: 2, reps: 8 },
      { name: 'Peitoral Cross Soco Baixo 3x6 (mt pes)', sets: 3, reps: 6 },
      { name: 'Crucifixo Halter', sets: 4, reps: 10 },
      { name: 'Supino Fechado Halter', sets: 3, reps: 10 },
      { name: 'Triceps Testa W', sets: 2, reps: 10 },
      { name: 'Triceps Corda 3x10/15 -30%', sets: 3, reps: 10 },
      { name: 'Triceps Paralelas (falha)', sets: 1, reps: 99 },
    ],
  },
  gyms: [
    { name: 'Gym 1' },
    { name: 'Gym 2' },
  ],
  sheetsWebAppUrl: 'https://script.google.com/macros/s/AKfycbxhqmzqSctgcEyD72E78I5UXHXx9x7Gidev7HYTOlPkwZsCjoE1xMOyX-vI07m_dnU/exec',
};

if (typeof module !== 'undefined') module.exports = { CONFIG };
